services:
  # db:
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_PASSWORD: example
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   networks:
  #     - appNetwork

  jekyll:
    image: bretfisher/jekyll-serve
    volumes:
      - ./codigo/src/main/resources/site:/site
    ports:
      - 4000:4000
    networks:
      - appNetwork

  # app:
  #   image: maven:3.6.3-openjdk-11
  #   volumes:
  #     - .:/usr/src/mymaven
  #   working_dir: /usr/src/mymaven
  #   command: mvn clean install
  #   depends_on:
  #     - db
  #   networks:
  #     - appNetwork

volumes:
  postgres_data:

networks:
  appNetwork:
    driver: bridge
