services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: pru
      POSTGRES_USER: pru
      POSTGRES_PASSWORD: 123
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./codigo/src/main/resources/sql/create.sql:/docker-entrypoint-initdb.d/create.sql
    ports:
      - 5432:5432
    networks:
      - appNetwork

  jekyll:
    image: bretfisher/jekyll-serve
    volumes:
      - ./codigo/src/main/resources/site:/site
    ports:
      - 4000:4000
    networks:
      - appNetwork

  scrapper:
    image: scrapper
    volumes:
      - ./codigo/src/main/resources/scrapper:/app
    build: 
      context: ./codigo/src/main/resources/scrapper
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    networks:
      - appNetwork



volumes:
  postgres_data:

networks:
  appNetwork:
    driver: bridge
